Fix local setup (#1287)
Place datasource and flyway config under the spring config in applicaiton.local

spring:
   datasource: ...
   flyway: ...

otherwise it will use the datasource in application.yml
which has sslmode=verify-full in the url

this fixes a local setup issue:

PSQLException: The server does not support SSL.